### ISSUE TITLE
Multiple Versions of "Same" Objects

### ISSUE THREAD

**Issue by KarmicJohn** [mattlisiv/mindbody-api-java#1]
I like what you're after here, but there are some challenges around how these WSDLs are put together. 

Was hoping to switch to this for v5.1, as my home-grown client is outdated. Probably not a best practice, but previously I've condensed the WSDLs down to a single WSDL and was able to keep one version of the duplicated objects (like ArrayOfInt).

For example, it's a bit convoluted to pull out the ArrayOfInt values for ProgramTypes from the SiteService and not be able to use that object in the Appointment service, due to the type, even though they are essentially the same objects.

Not even sure if that makes sense, but would love to hear if you're planning on actively maintaining this, could see the value in the above, and/or would be open to help in contributing something to this effect.

(Also open to the idea that I'm completely missing an alternative solution that bypasses the above issue and gets this to work, as-is)  :)

Thanks,
John

**Comment by mattlisiv** [comment]
Hi @KarmicJohn ,

Thanks for checking out the library. I definitely have noticed the issues that you mentioned with duplicate object types that cannot be reused among services. Because I had used an auto-generation tool, there was no analysis to condense these types.

My goal is to break out the reusable objects like ArrayOfInt into a generic namespace that can be reused among the WSDLs rather than consolidate to a single WSDL. I'm sure both options could have their benefits and drawbacks.

This is one of a few projects I am working on outside of my job, so I cannot guarantee anything, but I was hoping to accomplish this within the next couple of weeks. I am totally open to collaboration as well so feel free to open a pull request if you are feeling up to it!

Best,
Matt

**Comment by KarmicJohn** [comment]
Will definitely stay tuned in here, and hope to have something to contribute along the way. 👍
